<?php

    return [
        [
            'nome' => 'Leonardo',
            'cognome' => 'DiCaprio',
            'data_nascita' => '1974-11-11',
            'nazionalità' => 'Statunitense',
            'biografia' => 'Attore e produttore noto per Titanic e Inception.',
            'foto_url' => 'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcSdkHQcFIHa5n0k01C8UVuA4IFUyVT2roDq6W6vYsMSBv9V2aIXX1vyDTY_drh82PqkPjKRtyTVtC0vyoY',
        ],
        [
            'nome' => 'Penélope',
            'cognome' => 'Cruz',
            'data_nascita' => '1974-04-28',
            'nazionalità' => 'Spagnola',
            'biografia' => 'Attrice premiata, celebre per film di Almodóvar.',
            'foto_url' => 'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcT2zaQXeGIm4H8_NLH5A_kbfEpLD3YciH1LZTLTZeqlLf4sIdX_Km4KOsWIW21O8q5hNyj5kPQaBVh1Mso',
        ],
        [
            'nome' => 'Mahershala',
            'cognome' => 'Ali',
            'data_nascita' => '1974-02-16',
            'nazionalità' => 'Statunitense',
            'biografia' => 'Due Oscar per Moonlight e Green Book.',
            'foto_url' => 'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcSZX3t39muLR53mC7clwhDAG3EyzTwRdWmsF6cAZPUyKOSV78zF8l7gVYFVWybRLp2RtlHBc1WWB6A_6EqjHS6fQKV3GxHIx3D8glsywBdnSq4Q6hW6itEMMPOtbU3C5pASdIB8CEvIVBeM',
        ],
        [
            'nome' => 'Sofia',
            'cognome' => 'Boutella',
            'data_nascita' => '1982-04-03',
            'nazionalità' => 'Algerina',
            'biografia' => 'Attrice e ballerina, nota per Kingsman.',
            'foto_url' => 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRr8qgNaIPiRjegMfO4itqBrF10ey-28lZ5WWZtiqnERekhnGodqgajn6BoFVh2P6Ed0yhOeKGBbSZwrVDRcBSHAw',
        ],
        [
            'nome' => 'Toni',
            'cognome' => 'Servillo',
            'data_nascita' => '1959-01-25',
            'nazionalità' => 'Italiana',
            'biografia' => 'Attore noto per La grande bellezza.',
            'foto_url' => 'https://www.lavanguardia.com/peliculas-series/images/profile/1959/1/w1280/zHMSH7YrfQJFcdPNbZ42l5sZRLn.jpg',
        ],
        [
            'nome' => 'Cate',
            'cognome' => 'Blanchett',
            'data_nascita' => '1969-05-14',
            'nazionalità' => 'Australiana',
            'biografia' => 'Attrice pluripremiata, nota per Blue Jasmine.',
            'foto_url' => 'https://upload.wikimedia.org/wikipedia/commons/6/68/Cate_Blanchett_at_81st_Venice_International_Film_Festival_2.jpg',
        ],
        [
            'nome' => 'Daniel',
            'cognome' => 'Day-Lewis',
            'data_nascita' => '1957-04-29',
            'nazionalità' => 'Britannica',
            'biografia' => 'Tre Oscar come miglior attore.',
            'foto_url' => 'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcSLbvNHasIvbST7Pr0DkPlqam71zX-SY2_zGPAo5tj9KuJzAmm9uRHEeJnVlEPuMBrELi8ShiV494wAnKg',
        ],
        [
            'nome' => 'Lupita',
            'cognome' => 'Nyong\'o',
            'data_nascita' => '1983-03-01',
            'nazionalità' => 'Keniota',
            'biografia' => 'Premio Oscar per 12 anni schiavo.',
            'foto_url' => 'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRovnXWW7pFWV_gvGJpZ2MtWlp38BJqUl40GjVixBTbhqEcMsc2FRRzI0cWcItYDQcFq5x-_fHUHLcoFTU',
        ],
        [
            'nome' => 'Javier',
            'cognome' => 'Bardem',
            'data_nascita' => '1969-03-01',
            'nazionalità' => 'Spagnola',
            'biografia' => 'Oscar per Non è un paese per vecchi.',
            'foto_url' => 'https://hips.hearstapps.com/hmg-prod/images/gettyimages-2181949322-1-6819dcb4b681a.jpg?crop=0.670xw:1.00xh;0.154xw,0&resize=1120:*',
        ],
        [
            'nome' => 'Tilda',
            'cognome' => 'Swinton',
            'data_nascita' => '1960-11-05',
            'nazionalità' => 'Britannica',
            'biografia' => 'Attrice eclettica, nota per ruoli visionari.',
            'foto_url' => 'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcQkM7POMPeXDQ7lyosVzAJEsf1OkoF_oHcGViDN7ZWNDwznwiA5RhLNNaAEmBukSf78zpLgKcHxQicboaI',
        ],
        [
            'nome' => 'Pierfrancesco',
            'cognome' => 'Favino',
            'data_nascita' => '1969-08-24',
            'nazionalità' => 'Italiana',
            'biografia' => 'Attore italiano noto per Romanzo Criminale.',
            'foto_url' => 'https://hips.hearstapps.com/hmg-prod/images/pierfrancesco-favino-attends-a-photocall-for-the-movie-news-photo-1745776765.pjpeg?crop=1.00xw:0.668xh;0,0&resize=1200:*',
        ],
        [
            'nome' => 'Natalie',
            'cognome' => 'Portman',
            'data_nascita' => '1981-06-09',
            'nazionalità' => 'Statunitense',
            'biografia' => 'Oscar per Il cigno nero.',
            'foto_url' => 'https://encrypted-tbn2.gstatic.com/licensed-image?q=tbn:ANd9GcT4c6GCztNxiUSaCiQxZijKjG7Or8t0WbfsII2t7U-UW8kOkP40LmE0V8fvfNH5JQCaXXIjukw7aZM4kcw',
        ],
        [
            'nome' => 'Omar',
            'cognome' => 'Sy',
            'data_nascita' => '1978-01-20',
            'nazionalità' => 'Francese',
            'biografia' => 'Celebre per Quasi amici.',
            'foto_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Omar_Sy_%282020%29.jpg/960px-Omar_Sy_%282020%29.jpg',
        ],
        [
            'nome' => 'Frances',
            'cognome' => 'McDormand',
            'data_nascita' => '1957-06-23',
            'nazionalità' => 'Statunitense',
            'biografia' => 'Tre Oscar come miglior attrice.',
            'foto_url' => 'https://image.tmdb.org/t/p/w500/r0A7hZsM1zuavTr0jN7bwmBcliR.jpg',
        ],
        [
            'nome' => 'Riccardo',
            'cognome' => 'Scamarcio',
            'data_nascita' => '1979-11-13',
            'nazionalità' => 'Italiana',
            'biografia' => 'Attore italiano noto per Tre metri sopra il cielo.',
            'foto_url' => 'https://encrypted-tbn1.gstatic.com/licensed-image?q=tbn:ANd9GcTPShl5u4Sf8YMZuNypReAZGnMU7CmZj9eZ7otKZaWe36V6NAI_DyhG2DHGvrs2MEyeWinKvg4_6w1k_AA',
        ],
        [
            'nome' => 'Audrey',
            'cognome' => 'Tautou',
            'data_nascita' => '1976-08-09',
            'nazionalità' => 'Francese',
            'biografia' => 'Famosa per Il favoloso mondo di Amélie.',
            'foto_url' => 'https://m.media-amazon.com/images/M/MV5BMTYzOTgyNjk1Nl5BMl5BanBnXkFtZTcwNjMwMjI1OQ@@._V1_FMjpg_UX1000_.jpg',
        ],
        [
            'nome' => 'Chiwetel',
            'cognome' => 'Ejiofor',
            'data_nascita' => '1977-07-10',
            'nazionalità' => 'Britannica',
            'biografia' => 'Noto per 12 anni schiavo.',
            'foto_url' => 'https://encrypted-tbn3.gstatic.com/licensed-image?q=tbn:ANd9GcTxqt7O8YCwcsUrkHRxNG4qDH8bUuprWOEB0koyoA4LwURL-_aOVC8ncD-FMvF4Blw4Hae7454TG7VHUkU',
        ],
        [
            'nome' => 'Asia',
            'cognome' => 'Argento',
            'data_nascita' => '1975-09-20',
            'nazionalità' => 'Italiana',
            'biografia' => 'Attrice e regista italiana.',
            'foto_url' => 'https://www.cdastudiodinardo.com/backoffice/ownimage/hi_20251231481_asia_2.jpg',
        ],
        [
            'nome' => 'Gael',
            'cognome' => 'García Bernal',
            'data_nascita' => '1978-11-30',
            'nazionalità' => 'Messicana',
            'biografia' => 'Attore noto per Amores Perros.',
            'foto_url' => 'https://static2.iodonna.it/wp-content/uploads/2019/08/gael-1-ANSA.jpg?v=1226385',

        ],
    ];